---
server:
  port: 8888
  
security:
  basic:
    enabled: true
  user:
    name: alex.gera
    password: alex.gera
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zobarov/edu-springcloud-configserver-git-ire-tolls
          #username: uname
          #password: pwd
          search-paths: 
          - 'station*'
          repos:
            perf:
              pattern:
              - '*/perf'
              uri: https://github.com/zobarov/edu-springcloud-configserver-git-ire-tolls-perf
              search-paths:
              - 'station*'
        encrypt:
          enabled: false
              
            